export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',

  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',

  TASK_COMMENT_ADDED = 'TASK_COMMENT_ADDED',

  TASK_DUE_SOON = 'TASK_DUE_SOON',

  MENTIONED = 'MENTIONED',
}
